### ISSUE TITLE
No event coming back when I come back to my app after sharing on Instagram

### ISSUE THREAD

**Issue by kyazdani** [DaVikingCode/Instagram-ANE#3]
Hi,

thanks for the work on the extension. I'm not getting an event back when I have shared a post. I'm able to share on iOS but then nothing happens. Any ideas?

Thanks.

**Comment by kollehel** [comment]
Hi,

I have the same problem, the InstagramEvent is never fired after sharing the image. Any news how could it be solved?

Thanks,
Lehel

**Comment by pixeltwitchgames** [comment]
Same issue here

**Comment by pixeltwitchgames** [comment]
The ANE no longer compiles into my iOS project... I get an error: 

'An implementation for native extension 'com.davikingcode.Instagram-ANE' required by the application was not found for the target platform'

**Comment by Stortof** [comment]
Hi Aymeric,
Big thank for this great extension!
The event "InstagramEvent.OK", is not fired for me on IOS with the latest version of your ANE.
When should it be fired? when we come back to the app? is there something specific to do in IOS for this?

**Comment by alamboley** [comment]
Hey does it work with the previous version? Because I didn't change anything on that part (normally...)

**Comment by Stortof** [comment]
I did not try with the previous version.

**Comment by alamboley** [comment]
Ok, perhaps something change with latest Instagram app. I will be on holidays tonight, and I won't be able to give it a try before 3 weeks :/

**Comment by Stortof** [comment]
No problem...bonnes vacances !! :)

**Comment by alamboley** [comment]
Merci :) I reopened this issue... just for not forgetting.

**Comment by Stortof** [comment]
Salut Aymeric, any idea for this issue ? Can I help you with a test ?

**Comment by alamboley** [comment]
It should be fixed now :)

**Comment by Stortof** [comment]
Merci ! :)
