### ISSUE TITLE
Not caption is being received on Instagram on iOS,

### ISSUE THREAD

**Issue by dannycortesv** [DaVikingCode/Instagram-ANE#4]
Not caption is being received on Instagram on iOS, this was working on previous versions of iOS, but not on the latest one :/

**Comment by Stortof** [comment]
It seems it's the same on Android 5.0...maybe related to an Instagram app update ?

**Comment by alamboley** [comment]
Unfortunately it's no more possible since 5 months due to Instagram API http://developers.instagram.com/post/125972775561/removing-pre-filled-captions-from-mobile-sharing (same change than Facebook).

**Comment by Stortof** [comment]
Merci pour l'info Aymeric :)

**Comment by dannycortesv** [comment]
Gracias Aymeric! :)
