### ISSUE TITLE
instagram.isInstalled() always returns false on iOS & AIR 20

### ISSUE THREAD

**Issue by inaffect-ag** [DaVikingCode/Instagram-ANE#5]
when i try to check if instagram is installed on iOS 9, i always get a return "false" - even if instagram is installed.
does anybody have this issue as well?

**Comment by alamboley** [comment]
No, it's working fine on my iOS 9.2 with latest Instagram app.

**Comment by inaffect-ag** [comment]
thanks! but i just reinstalled instagram, added the fresh ane but still i get "false" when checking...
can you think of some restrictions??

**Comment by alamboley** [comment]
Unfortunately, I'm not aware of any restrictions... Are you using AIR 20 ?

**Comment by inaffect-ag** [comment]
yes, air 20
as i understand, there's nothing in the app description xml, right?

**Comment by alamboley** [comment]
Yes nothing to add, just the ANE. I didn't test with AIR 20, due to all its issues I stayed on AIR 19. Would you mind to test on that previous version?

**Comment by inaffect-ag** [comment]
that did the trick: air sdk 19 works. - thanks for taking your time!

**Comment by alamboley** [comment]
Ok I suppose that I will need to recompile the ANE with AIR 20, but I'll wait the SDK to be more stable... Probably AIR 21.

**Comment by alamboley** [comment]
Adding this code behind in the *-app.xml seems to do the trick (thanks Paul)!
```xml
<iPhone>
	<InfoAdditions><![CDATA[
		<key>LSApplicationQueriesSchemes</key>
		<array>
			<string>instagram</string>
		</array>
	]]></InfoAdditions>
</iPhone>
```

**Comment by Paul-Ollivier** [comment]
You're welcome : >

**Comment by alamboley** [comment]
added in the readme!
