### ISSUE TITLE
"Unable to load image"on Android 6.0.1

### ISSUE THREAD

**Issue by kollehel** [DaVikingCode/Instagram-ANE#6]
Hi,

On Android 6.0.1 it always says  "Unable to load image". I tried everything, added the permissions as well.
But on Android 4.3 it works fine using the same apk.
What can be the problem?

Thank you and best regards,
Lehel

**Comment by alamboley** [comment]
Hey,

The error is on AS3 side? Are you using AIR 20? I compiled the ANE with AIR 19.

**Comment by kollehel** [comment]
I tried it with both 19.0.0.193 and 20.0.0.196 AIR versions. 
The error isn't appearing on ActionScript level, but rather in Instagram, I think. Basically it is shown in a small rectangle on the bottom  of the screen, while the Android switches the game window to Instagram window. It shows this message, then automatically switches back to the game and fires the InstagramEvent.OK event.
But again, this is only in case of Android 6.0.1. Under Android 4.3 it works fine.

**Comment by gsynuh** [comment]
Yeah this is an error displayed by instagram itself - in an Android text overlay (not a popup I don't know how its called)

Anyway I used to have this error, are you sending a square image? is it more than 640x640 ?

**Comment by kollehel** [comment]
I was trying to share a BitmapData  having dmensions exactly 640x640.

**Comment by kollehel** [comment]
Any news regarding this issue?

**Comment by alamboley** [comment]
Could you attach logs from logcat, or DDMS, or Monitor? Thanks.

**Comment by kollehel** [comment]
Hi,

Sure, here are the logs from logcat. It contains only the logs from the beginning of pushing a button in the app to start sharing. It also contains some traces from the app, since it was built in debug mode. Those logs start with "I/air.MyTestApp:".

Thanks,
Lehel

[logcat.txt](https://github.com/DaVikingCode/Instagram-ANE/files/272389/logcat.txt)

**Comment by alamboley** [comment]
Thanks, could you try adding `android.permission.READ_EXTERNAL_STORAGE` ?

**Comment by kollehel** [comment]
I added it, and still the same happens. These logs are already after adding that permission.

**Comment by alamboley** [comment]
I compiled it with AIR 21, could you try again https://www.dropbox.com/s/6wejqfn5k2q5k3t/Instagram.ane?dl=0?

**Comment by kollehel** [comment]
I'm afraid it's still the same. :(

[logcat.txt](https://github.com/DaVikingCode/Instagram-ANE/files/272438/logcat.txt)

**Comment by alamboley** [comment]
Well I found this topic http://stackoverflow.com/q/33721235/1372378 tell me if it solves your issue.

**Comment by kollehel** [comment]
oh, cool, it's working! Instagram needed that read permission. :D
Thank you very much for your help!

**Comment by alamboley** [comment]
Glad to know! So you needed to change settings on Instagram app?
Please, tell me what I've to add in the README so people won't have this issue ;)

**Comment by kollehel** [comment]
Well, in fact I have never used the Instagram app on that device to post something, I just installed it and tried using your Instagram.ane. But when you first open the Instagram app (not with the ane), and you try to post something, an Android native popup appears asking you if you want to allow it to access  your files, and you have to allow it. Here is also a screenshot of it.
![read_permission](https://cloud.githubusercontent.com/assets/8259342/15393607/e49d4ca0-1dd6-11e6-968c-69ff897ccca2.png)

**Comment by alamboley** [comment]
Ok, good to know, thanks! :)
